ServerEvents.recipes(event => {
    event.shapeless('oak_planks', ['2x oak_slab'])
    event.shapeless('spruce_planks', ['2x spruce_slab'])
    event.shapeless('birch_planks', ['2x birch_slab'])
    event.shapeless('jungle_planks', ['2x jungle_slab'])
    event.shapeless('acacia_planks', ['2x acacia_slab'])
    event.shapeless('dark_oak_planks', ['2x dark_oak_slab'])
    event.shapeless('mangrove_planks', ['2x mangrove_slab'])
    event.shapeless('crimson_planks', ['2x crimson_slab'])
    event.shapeless('warped_planks', ['2x warped_slab'])
    event.shapeless('ad_astra:aeronos_planks', ['2x ad_astra:aeronos_slab'])
    event.shapeless('ad_astra:strophar_planks', ['2x ad_astra:strophar_slab'])
    event.shapeless('ad_astra:glacian_planks', ['2x ad_astra:glacian_slab'])
    event.shapeless('botania:livingwood_log', ['4x immersive_weathering:botania/livingwood_bark'])
    event.shapeless('2x botania:livingwood_planks', ['botania:livingwood_log'])
    })
