ServerEvents.recipes(event => {
    event.remove({ id: 'minecraft:oak_planks' })
    event.remove({ id: 'minecraft:spruce_planks' })
    event.remove({ id: 'minecraft:birch_planks' })
    event.remove({ id: 'minecraft:jungle_planks' })
    event.remove({ id: 'minecraft:acacia_planks' })
    event.remove({ id: 'minecraft:dark_oak_planks' })
    event.remove({ id: 'minecraft:mangrove_planks' })
    event.remove({ id: 'minecraft:crimson_planks' })
    event.remove({ id: 'minecraft:warped_planks' })
    event.remove({ id: 'ad_astra:recipes/aeronos_planks' })
    event.remove({ id: 'ad_astra:recipes/strophar_planks' })
    event.remove({ id: 'ad_astra:recipes/glacian_planks' })
    event.remove({ id: 'minecraft:oak_slab' })
    event.remove({ id: 'minecraft:spruce_slab' })
    event.remove({ id: 'minecraft:brich_slab' })
    event.remove({ id: 'minecraft:jungle_slab' })
    event.remove({ id: 'minecraft:acacia_slab' })
    event.remove({ id: 'minecraft:dark_oak_slab' })
    event.remove({ id: 'minecraft:mangrove_slab' })
    event.remove({ id: 'minecraft:crimson_slab' })
    event.remove({ id: 'minecraft:warped_slab' })
    event.remove({ id: 'ad_astra:recipes/aeronos_slab' })
    event.remove({ id: 'ad_astra:recipes/strophar_slab' })
    event.remove({ id: 'ad_astra:glacian_slab' })
    event.remove({ id: 'botania:livingwood_planks' })
})
ServerEvents.recipes(event => {
    event.shapeless('oak_planks', ['2x oak_slab'])
    event.shapeless('spruce_planks', ['2x spruce_slab'])
    event.shapeless('birch_planks', ['2x birch_slab'])
    event.shapeless('jungle_planks', ['2x jungle_slab'])
    event.shapeless('acacia_planks', ['2x acacia_slab'])
    event.shapeless('dark_oak_planks', ['2x dark_oak_slab'])
    event.shapeless('mangrove_planks', ['2x mangrove_slab'])
    event.shapeless('crimson_planks', ['2x crimson_slab'])
    event.shapeless('warped_planks', ['2x warped_slab'])
    event.shapeless('ad_astra:aeronos_planks', ['2x ad_astra:aeronos_slab'])
    event.shapeless('ad_astra:strophar_planks', ['2x ad_astra:strophar_slab'])
    event.shapeless('ad_astra:glacian_planks', ['2x ad_astra:glacian_slab'])
    event.shapeless('botania:livingwood_log', ['4x immersive_weathering:botania/livingwood_bark'])
    event.shapeless('2x botania:livingwood_planks', ['botania:livingwood_log'])
    })

