// Vanilla
REIEvents.groupEntries(event => {
    event.groupItemsByTag('kubejs:rei_groups/colored_wool', 'Colored Wool', 'minecraft:wool');
    event.groupItemsByTag('kubejs:rei_groups/logs', 'Logs', 'minecraft:logs');
    event.groupItemsByTag('kubejs:rei_groups/planks', 'Planks', 'minecraft:planks');
    event.groupItemsByTag('kubejs:rei_groups/colored_glass', 'Stained Glass', 'c:stained_glass');
    event.groupItemsByTag('kubejs:rei_groups/colored_concrete', 'Colored Concrete', 'c:concrete_blocks');
    event.groupItemsByTag('kubejs:rei_groups/slabs', 'Slabs', 'minecraft:slabs');
    event.groupItemsByTag('kubejs:rei_groups/stairs', 'Stairs', 'minecraft:stairs');
    event.groupItemsByTag('kubejs:rei_groups/leaves', 'Leaves', 'minecraft:leaves');
    event.groupItemsByTag('kubejs:rei_groups/buttons', 'Buttons', 'minecraft:buttons');
    event.groupItemsByTag('kubejs:rei_groups/pressure_plates', 'Pressure Plates', 'minecraft:pressure_plates');
    event.groupItemsByTag('kubejs:rei_groups/seeds', 'Seeds', '#c:seeds');
    event.groupItemsByTag('kubejs:rei_groups/saplings', 'Saplings', 'minecraft:saplings');
    event.groupItemsByTag('kubejs:rei_groups/glass_panes', 'Glass Panes', 'c:glass_panes');
    event.groupItemsByTag('kubejs:rei_groups/ores', 'Ores', 'c:ores');
    event.groupItemsByTag('kubejs:rei_groups/raw_ores', 'Raw Ores', 'c:raw_materials');
    event.groupItemsByTag('kubejs:rei_groups/dusts', 'Dusts', "c:dusts");
    event.groupItemsByTag('kubejs:rei_groups/ingots', 'Ingots', "c:ingots");
    event.groupItemsByTag('kubejs:rei_groups/plates', 'Plates', "c:plates");
    event.groupItemsByTag('kubejs:rei_groups/storage_blocks', 'Blocks', "c:storage_blocks");
})
// Gregtech
REIEvents.groupEntries(event => {
    event.groupItemsByTag('kubejs:rei_groups/salt_ores', 'Salt Ores', 'c:salt_ores');
    event.groupItemsByTag('kubejs:rei_groups/aluminium_ores', 'Aluminium Ores', 'c:aluminium_ores');
    event.groupItemsByTag('kubejs:rei_groups/beryllium_ores', 'Beryllium Ores', 'c:beryllium_ores');
    event.groupItemsByTag('kubejs:rei_groups/lead_ores', 'Lead Ores', 'c:lead_ores');
    event.groupItemsByTag('kubejs:rei_groups/lithium_ores', 'Lithium Ores', 'c:lithium_ores');
    event.groupItemsByTag('kubejs:rei_groups/molybdenum_ores', 'Molybdenum Ores', 'c:molybdenum_ores');
    event.groupItemsByTag('kubejs:rei_groups/lead_ores', 'Lead Ores', 'c:lead_ores');
    event.groupItemsByTag('kubejs:rei_groups/neodymium_ores', 'Neodymium Ores', 'c:neodymium_ores');
    event.groupItemsByTag('kubejs:rei_groups/nickel_ores', 'Nickel Ores', 'c:nickel_ores');
    event.groupItemsByTag('kubejs:rei_groups/palladium_ores', 'Palladium Ores', 'c:palladium_ores');
    event.groupItemsByTag('kubejs:rei_groups/platinum_ores', 'Platinum Ores', 'c:platinum_ores');
    event.groupItemsByTag('kubejs:rei_groups/plutonium_ores', 'Plutonium Ores', 'c:plutonium_ores');
    event.groupItemsByTag('kubejs:rei_groups/silver_ores', 'Silver Ores', 'c:silver_ores');
    event.groupItemsByTag('kubejs:rei_groups/sulfur_ores', 'Sulfur Ores', 'c:sulfur_ores');
    event.groupItemsByTag('kubejs:rei_groups/thorium_ores', 'Thorium Ores', 'c:thorium_ores');
    event.groupItemsByTag('kubejs:rei_groups/tin_ores', 'Tin Ores', 'c:tin_ores');
    event.groupItemsByTag('kubejs:rei_groups/naquadah_ores', 'Naquadah Ores', 'c:naquadah_ores');
    event.groupItemsByTag('kubejs:rei_groups/almandine_ores', 'Almandine Ores', 'c:almandine_ores');
    event.groupItemsByTag('kubejs:rei_groups/asbestos_ores', 'Asbestos Ores', 'c:asbestos_ores');
    event.groupItemsByTag('kubejs:rei_groups/hematite_ores', 'Hematite Ores', 'c:hematite_ores');
    event.groupItemsByTag('kubejs:rei_groups/blue_topaz_ores', 'Blue Topaz Ores', 'c:blue_topaz_ores');
    event.groupItemsByTag('kubejs:rei_groups/goethite_ores', 'Goethite Ores', 'c:goethite_ores');
    event.groupItemsByTag('kubejs:rei_groups/calcite_ores', 'Calcite Ores', 'c:calcite_ores');
    event.groupItemsByTag('kubejs:rei_groups/cassiterite_ores', 'Cassiterite Ores', 'c:cassiterite_ores');
    event.groupItemsByTag('kubejs:rei_groups/cassiterite_sand_ores', 'Cassiterite Sand Ores', 'c:cassiterite_sand_ores');
    event.groupItemsByTag('kubejs:rei_groups/chalcopyrite_ores', 'Chalcopyrite Ores', 'c:chalcopyrite_ores');
    event.groupItemsByTag('kubejs:rei_groups/chromite_ores', 'Chromite Ores', 'c:chromite_ores');
    event.groupItemsByTag('kubejs:rei_groups/cinnabar_ores', 'Cinnabar Ores', 'c:cinnabar_ores');
    event.groupItemsByTag('kubejs:rei_groups/cobaltite_ores', 'Cobaltite Ores', 'c:cobaltite_ores');
    event.groupItemsByTag('kubejs:rei_groups/sheldonite_ores', 'Sheldonite Ores', 'c:cooperite_ores');
    event.groupItemsByTag('kubejs:rei_groups/galena_ores', 'Galena Ores', 'c:galena_ores');
    event.groupItemsByTag('kubejs:rei_groups/garnierite_ores', 'Garnierite Ores', 'c:garnierite_ores');
    event.groupItemsByTag('kubejs:rei_groups/green_sapphire_ores', 'Green Sapphire Ores', 'c:green_sapphire_ores');
    event.groupItemsByTag('kubejs:rei_groups/grossular_ores', 'Grossular Ores', 'c:grossular_ores');
    event.groupItemsByTag('kubejs:rei_groups/ilmenite_ores', 'Ilmenite Ores', 'c:ilmenite_ores');
    event.groupItemsByTag('kubejs:rei_groups/bauxite_ores', 'Bauxite Ores', 'c:bauxite_ores');
    event.groupItemsByTag('kubejs:rei_groups/lazurite_ores', 'Lazurite Ores', 'c:lazurite_ores');
    event.groupItemsByTag('kubejs:rei_groups/magnesite_ores', 'Magnesite Ores', 'c:magnesite_ores');
    event.groupItemsByTag('kubejs:rei_groups/magnetite_ores', 'Magnetite Ores', 'c:magnetite_ores');
    event.groupItemsByTag('kubejs:rei_groups/molybdenite_ores', 'Molybdenite Ores', 'c:molybdenite_ores');
    event.groupItemsByTag('kubejs:rei_groups/powellite_ores', 'Powellite Ores', 'c:powellite_ores');
    event.groupItemsByTag('kubejs:rei_groups/pyrite_ores', 'Pyrite Ores', 'c:pyrite_ores');
    event.groupItemsByTag('kubejs:rei_groups/pyrolusite_ores', 'Pyrolusite Ores', 'c:oyrolusite_ores');
    event.groupItemsByTag('kubejs:rei_groups/pyrope_ores', 'Pyrope Ores', 'c:pyrope_ores');
    event.groupItemsByTag('kubejs:rei_groups/rock_salt_ores', 'Rock Salt Ores', 'c:rock_salt_ores');
    event.groupItemsByTag('kubejs:rei_groups/ruby_ores', 'Ruby Ores', 'c:ruby_ores');
    event.groupItemsByTag('kubejs:rei_groups/saltpeter_ores', 'Saltpeter Ores', 'c:saltpeter_ores');
    event.groupItemsByTag('kubejs:rei_groups/sapphire_ores', 'Sapphire Ores', 'c:sapphire_ores');
    event.groupItemsByTag('kubejs:rei_groups/scheelite_ores', 'Scheelite Ores', 'c:scheelite_ores');
    event.groupItemsByTag('kubejs:rei_groups/sodalite_ores', 'Sodalite Ores', 'c:sodalite_ores');
    event.groupItemsByTag('kubejs:rei_groups/tantalite_ores', 'Tantalite Ores', 'c:tantalite_ores');
    event.groupItemsByTag('kubejs:rei_groups/spessartine_ores', 'Spessartine Ores', 'c:spessartine_ores');
    event.groupItemsByTag('kubejs:rei_groups/sphalerite_ores', 'Sphalerite Ores', 'c:sphalerite_ores');
    event.groupItemsByTag('kubejs:rei_groups/stibnite_ores', 'Stibnite Ores', 'c:stibnite_ores');
    event.groupItemsByTag('kubejs:rei_groups/tetrahedrite_ores', 'Tetrahedrite Ores', 'c:tetrahedrite_ores');
    event.groupItemsByTag('kubejs:rei_groups/topaz_ores', 'Topaz Ores', 'c:topaz_ores');
    event.groupItemsByTag('kubejs:rei_groups/tungstate_ores', 'Tungstate Ores', 'c:tungstate_ores');
    event.groupItemsByTag('kubejs:rei_groups/wulfute_ores', 'Wulfenite Ores', 'c:wulfenite_ores');
    event.groupItemsByTag('kubejs:rei_groups/yellow_limonite_ores', 'Yellow Limonite Ores', 'c:yellow_limonite_ores');
    event.groupItemsByTag('kubejs:rei_groups/nether_star_ores', 'Nether Quartz Ores', 'c:nether_quartz_ores');
    event.groupItemsByTag('kubejs:rei_groups/certus_quartz_ores', 'Certus Quartz Ores', 'c:certus_quartz_ores');
    event.groupItemsByTag('kubejs:rei_groups/quartzite_ores', 'Quartzite Ores', 'c:quartzite_ores');
    event.groupItemsByTag('kubejs:rei_groups/graphite_ores', 'Graphite Ores', 'c:graphite_ores');
    event.groupItemsByTag('kubejs:rei_groups/bornite_ores', 'Bornite Ores', 'c:bornite_ores');
    event.groupItemsByTag('kubejs:rei_groups/chalcocite_ores', 'Chalcocite Ores', 'c:chalcocite_ores');
    event.groupItemsByTag('kubejs:rei_groups/realgar_ores', 'Realgar Ores', 'c:realgar_ores');
    event.groupItemsByTag('kubejs:rei_groups/bastnasite_ores', 'Bastnasite Ores', 'c:bastnasite_ores');
    event.groupItemsByTag('kubejs:rei_groups/pentlandite_ores', 'Pentlandite Ores', 'c:pentlandite_ores');
    event.groupItemsByTag('kubejs:rei_groups/spodumene_ores', 'Spodumene Ores', 'c:spodumene_ores');
    event.groupItemsByTag('kubejs:rei_groups/lepidolite_ores', 'Lepidolite Ores', 'c:lepidolite_ores');
    event.groupItemsByTag('kubejs:rei_groups/glauconite_sand_ores', 'Glauconite Sand Ores', 'c:glaconite_sand_ores');
    event.groupItemsByTag('kubejs:rei_groups/malachite_ores', 'Malachite Ores', 'c:malachite_ores');
    event.groupItemsByTag('kubejs:rei_groups/mica_ores', 'Mica Ores', 'c:mica_ores');
    event.groupItemsByTag('kubejs:rei_groups/barite_ores', 'Barite Ores', 'c:barite_ores');
    event.groupItemsByTag('kubejs:rei_groups/alunite_ores', 'Alunite Ores', 'c:alunite_ores');
    event.groupItemsByTag('kubejs:rei_groups/talc_ores', 'Talc Ores', 'c:talc_ores');
    event.groupItemsByTag('kubejs:rei_groups/soapstone_ores', 'Soapstone Ores', 'c:soapstone_ores');
    event.groupItemsByTag('kubejs:rei_groups/pyrochlore_ores', 'Pyrochlore Ores', 'c:pyrochlore_ores');
    event.groupItemsByTag('kubejs:rei_groups/oilsands_ores', 'Oilsands Ores', 'c:oilsands_ores');
    event.groupItemsByTag('kubejs:rei_groups/olivine_ores', 'Olivine Ores', 'c:olivine_ores');
    event.groupItemsByTag('kubejs:rei_groups/opal_ores', 'Opal Ores', 'c:opal_ores');
    event.groupItemsByTag('kubejs:rei_groups/amesthyst_ores', 'Amethyst Ores', 'c:amethyst_ores');
    event.groupItemsByTag('kubejs:rei_groups/apatite_ores', 'Apatite Ores', 'c:apatite_ores');
    event.groupItemsByTag('kubejs:rei_groups/tricalcium_phosphate_ores', 'Tricalcium Phosphate Ores', 'c:tricalcium_phosphate_ores');
    event.groupItemsByTag('kubejs:rei_groups/red_garnet_ores', 'Red Garnet Ores', 'c:red_garnet_ores');
    event.groupItemsByTag('kubejs:rei_groups/yellow_garnet_ores', 'Yellow Garnet Ores', 'c:yellow_garnet_ores');
    event.groupItemsByTag('kubejs:rei_groups/vanadium_magnetite_ores', 'Vanadium Magnetite Ores', 'c:vanadium_magnetite_ores');
    event.groupItemsByTag('kubejs:rei_groups/pollucite_ores', 'Pollucite Ores', 'c:pollucite_ores');
    event.groupItemsByTag('kubejs:rei_groups/bentonite_ores', 'Bentonite Ores', 'c:bentonite_ores');
    event.groupItemsByTag('kubejs:rei_groups/fullers_earth_ores', 'Fullers Earth Ores', 'c:fullers_earth_ores');
    event.groupItemsByTag('kubejs:rei_groups/pitchblende_ores', 'Pitchblende Ores', 'c:pitchblende_ores');
    event.groupItemsByTag('kubejs:rei_groups/monazite_ores', 'Monazite Ores', 'c:monazite_ores');
    event.groupItemsByTag('kubejs:rei_groups/trona_ores', 'Trona Ores', 'c:trona_ores');
    event.groupItemsByTag('kubejs:rei_groups/gypsum_ores', 'Gypsum Ores', 'c:gypsum_ores');
    event.groupItemsByTag('kubejs:rei_groups/zeolite_ores', 'Zeolite Ores', 'c:zeolite_ores');
    event.groupItemsByTag('kubejs:rei_groups/electrotine_ores', 'Electrotine Ores', 'c:electrotine_ores');
    event.groupItemsByTag('kubejs:rei_groups/diatomite_ores', 'Diatomite Ores', 'c:diatomite_ores');
    event.groupItemsByTag('kubejs:rei_groups/granitic_mineral_sand_ores', 'Granitic Mineral Sand Ores', 'c:granitic_mineral_sand_ores');
    event.groupItemsByTag('kubejs:rei_groups/garnet_sand_ores', 'Garnet Sand Ores', 'c:garnet_sand_ores');
    event.groupItemsByTag('kubejs:rei_groups/basaltic_mineral_sand_ores', 'Basaltic Mineralsand Ores', 'c:basaltic_minearal_sand_ores');
    event.groupItemsByTag('kubejs:rei_groups/kyanite_ores', 'Kyanite Ores', 'c:kyanite_ores');
})
