ServerEvents.recipes(event => {
    event.remove({ id: 'minecraft:oak_slab' })
    event.remove({ id: 'minecraft:spruce_slab' })
    event.remove({ id: 'minecraft:brich_slab' })
    event.remove({ id: 'minecraft:jungle_slab' })
    event.remove({ id: 'minecraft:acacia_slab' })
    event.remove({ id: 'minecraft:dark_oak_slab' })
    event.remove({ id: 'minecraft:mangrove_slab' })
    event.remove({ id: 'minecraft:crimson_slab' })
    event.remove({ id: 'minecraft:warped_slab' })
    event.remove({ id: 'ad_astra:recipes/aeronos_slab' })
    event.remove({ id: 'ad_astra:recipes/strophar_slab' })
    event.remove({ id: 'ad_astra:glacian_slab' })
    event.remove({ id: 'botania:livingwood_planks' })
    event.remove({ id: 'tconstruct:world/wood/greenheart/planks' })
    event.remove({ id: 'minecraft:chest' })
    event.remove({ id: 'botania:elven_trade/dragonstone' })
    event.remove({ id: 'gtceu:assembler/coil_cupronickel' })
    event.remove({ id: 'gtceu:assembler/coil_kanthal' })
    event.remove({ id: 'gtceu:assembler/coil_nichrome' })
    event.remove({ id: 'gtceu:assembler/coil_tungstensteel' })
    event.remove({ id: 'gtceu:assembler/coil_hssg' })
    event.remove({ id: 'gtceu:assembler/coil_naquadah' })
    event.remove({ id: 'gtceu:assembler/coil_trinium' })
    event.remove({ id: 'gtceu:assembler/coil_tritanium' })
    event.remove({ id: 'gtceu:compressor/compress_plate_dust_mica_pulp_' })
    aaaa
})
